(TechNinja AI Generated G-Code)
G21 ; Set units to millimeters
G90 ; Absolute positioning
G0 X10 Y10 ; Move to start position
G1 X20 Y20 F1000 ; Start writing
; Writing text: Hey '9173985952063, thank you for your purchase from TechNinja!
G0 X0 Y0 ; Return to origin
(Generated by TechNinja | AI Automation)
